/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SopRouteImport } from './routes/sop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'
import { Route as ApiSubmitRouteImport } from './routes/api/submit'
import { Route as ApiFetchUpiRouteImport } from './routes/api/fetch-upi'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const SopRoute = SopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitRoute = ApiSubmitRouteImport.update({
  id: '/api/submit',
  path: '/api/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchUpiRoute = ApiFetchUpiRouteImport.update({
  id: '/api/fetch-upi',
  path: '/api/fetch-upi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sop': typeof SopRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/api/fetch-upi': typeof ApiFetchUpiRoute
  '/api/submit': typeof ApiSubmitRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sop': typeof SopRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/api/fetch-upi': typeof ApiFetchUpiRoute
  '/api/submit': typeof ApiSubmitRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sop': typeof SopRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/api/fetch-upi': typeof ApiFetchUpiRoute
  '/api/submit': typeof ApiSubmitRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sop'
    | '/dashboard'
    | '/submit'
    | '/api/fetch-upi'
    | '/api/submit'
    | '/api/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sop'
    | '/dashboard'
    | '/submit'
    | '/api/fetch-upi'
    | '/api/submit'
    | '/api/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sop'
    | '/_authenticated/dashboard'
    | '/_authenticated/submit'
    | '/api/fetch-upi'
    | '/api/submit'
    | '/api/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SopRoute: typeof SopRoute
  ApiFetchUpiRoute: typeof ApiFetchUpiRoute
  ApiSubmitRoute: typeof ApiSubmitRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sop': {
      id: '/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof SopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit': {
      id: '/api/submit'
      path: '/api/submit'
      fullPath: '/api/submit'
      preLoaderRoute: typeof ApiSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-upi': {
      id: '/api/fetch-upi'
      path: '/api/fetch-upi'
      fullPath: '/api/fetch-upi'
      preLoaderRoute: typeof ApiFetchUpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SopRoute: SopRoute,
  ApiFetchUpiRoute: ApiFetchUpiRoute,
  ApiSubmitRoute: ApiSubmitRoute,
  ApiWebhookRoute: ApiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
